<a href="https://colab.research.google.com/github/HOSSENkhodadadi/Data_Science_Labs_Process_Methods/blob/main/Exercises/2_Numpy_Examples_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list3 = [[1, 2, 3 ],[4,5,6],[7,8,9]]

import numpy as np
arr3 = np.array(list3)

rowVec = np.array([1,2,3])
print(np.shape(rowVec))

columnVec = np.array([[0,1],[0,2],[0,3]])
print(np.shape(columnVec))




(3,)
(3, 2)


<ipython-input-18-e6852bd1b20a>:12: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(list3,dtype = np.float)


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
list3 = [[1, 2, 3 ],[4,5,6],[7,8,9]]
list3Array= np.array(list3,dtype = np.float16)
print(x)
a = np.ones((2,3))
print(a+300)
print(a + np.array([300], dtype = np.int16))
np.full((2,1),2.2)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[301. 301. 301.]
 [301. 301. 301.]]
[[301. 301. 301.]
 [301. 301. 301.]]


array([[2.2],
       [2.2]])

In [ ]:
print(np.linspace(2,9,8)) # (n-m+1)/p
print(np.arange(1,10,1)) #last excluded

print(np.random.normal(0,1,(5,))) #?
print(np.random.normal(0,1,5))
print(np.random.normal(0,1,(1,5)))

print(np.random.random((5,3)))
print(np.random.random((5,)))

[2. 3. 4. 5. 6. 7. 8. 9.]
[1 2 3 4 5 6 7 8 9]
[ 1.66868816  0.98583703 -0.1926939   1.14515065  0.75425738]
[ 0.40578276 -1.32456058 -0.75955167  1.01681941  0.96499965]
[[ 0.30409806 -2.11982834  0.24910188  0.27746988  0.10682013]]
[[0.84251121 0.80549879 0.86782087]
 [0.03420239 0.1310062  0.49337468]
 [0.6073058  0.64069341 0.32889645]
 [0.91936305 0.19867326 0.63108288]
 [0.57056055 0.08744568 0.07083303]]
[0.87022185 0.59857723 0.59523171 0.50280957 0.92860644]


In [ ]:
x = np.array([[2,3,4],[5,6,7]])

print(x.ndim)
print(x.shape)
print(x.size) # product of the shape values

2
(2, 3)
6


In [ ]:
x = np.array([[1,1],[2,2]])
y = np.array([[3,4],[6,5]])
print(x)
print(y)
print("\n")

#element-wise operation
print(x*y)
print("\n")

print(x/y)
print("\n")

#what is this
print(x,y)

[[1 1]
 [2 2]]
[[3 4]
 [6 5]]


[[ 3  4]
 [12 10]]


[[0 0]
 [0 0]]


[[1 1]
 [2 2]] [[3 4]
 [6 5]]


In [ ]:
#unary functions
#operation separately to each element of the array
#original array is not modified

x = np.array([[1,1],[2,-2]])
print(np.abs(x))

print(np.log(x))

print(np.sin(x))

print(np.exp(x))


[[1 1]
 [2 2]]
[[0.         0.        ]
 [0.69314718        nan]]
[[ 0.84147098  0.84147098]
 [ 0.90929743 -0.90929743]]
[[2.71828183 2.71828183]
 [7.3890561  0.13533528]]


<ipython-input-78-7c27f3e05994>:5: RuntimeWarning: invalid value encountered in log
  print(np.log(x))


In [ ]:
#Aggregate functions
import numpy as np
#argmax without value flattens all the arrays and counts from zero
x = np.array([[14,71],[210,430],[810,1]])
print(x)
print(x.sum(axis = 0))
print(x.argmax())


[[ 14  71]
 [210 430]
 [810   1]]
[1034  502]
4


In [ ]:
x = np.array([[14,71],[210,430],[810,1]])
x = np.arange(36).reshape(3,4,3)
print(x)

y = [  
[[1,2,3]],
[[1,2,3]],
[[1,2,3]]
]

arr = np.array(y)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [ ]:
# negative axis
# calcultes axis = axis %2 for negative numbers range between 0,-ndim
t = np.arange(1,11).reshape(2,5)
print(t)
t.sum(axis = -1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([15, 40])

In [ ]:
x = np.arange(1,19).reshape(3,2,3)
print(np.shape(x))
y = np.array([[14,71],[210,430],[810,1]])
y.shape


In [ ]:
#the aggregation dimension is removed from the 
# depth height width
x = np.arange(1,19).reshape(3,2,3)
print(x)
np.sort(x, axis = 0)
x.min(axis = 1)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [ ]:
# difference between .sort() and np.sort(x)
x = np.array([[14,71,5],[210,430,16],[810,1,46]])
np.sort(x, axis = -1)
np.argsort(x)


array([[2, 0, 1],
       [2, 0, 1],
       [1, 2, 0]])

In [ ]:
from sklearn.datasets import load_iris
X,y = load_iris(return_X_y = True)
#print(X)
X.shape
X.mean(axis = 1)
X.std(axis = 0)
print(x) #???

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(10,19).reshape(3,3)
print(x)
print(y)
np.dot(x,y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [ ]:
x = np.arange(1,10).reshape(3,3,1)
print(x)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [ ]:
x = np.random.random ((5,4,3))
print(x)
x [0,2,1]
x[0,2] #???
x [0,2,-1]
x[0,-2]

[[[0.49839292 0.43654151 0.05758376]
  [0.50787545 0.03710702 0.28183806]
  [0.52380096 0.58426149 0.21448375]
  [0.59503738 0.23376216 0.19298728]]

 [[0.78186582 0.26684149 0.54279811]
  [0.61818537 0.15727067 0.7205094 ]
  [0.745341   0.20333285 0.02694419]
  [0.28225235 0.97458637 0.64157097]]

 [[0.27051907 0.06361642 0.0313956 ]
  [0.98641757 0.91268992 0.64920814]
  [0.03143974 0.76618959 0.10897299]
  [0.8729383  0.79014281 0.27141584]]

 [[0.70404149 0.93042364 0.11685273]
  [0.28380193 0.45830349 0.43752581]
  [0.38174639 0.87280669 0.86177445]
  [0.84452553 0.1057951  0.7136519 ]]

 [[0.23186103 0.53044103 0.98945699]
  [0.1106622  0.00566483 0.70657366]
  [0.50324711 0.66960279 0.05143606]
  [0.08681412 0.59973345 0.30762414]]]


array([0.52380096, 0.58426149, 0.21448375])

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)
x[1:, 1:,1:]

[[[0.87886409 0.84759655 0.7698614 ]
  [0.09012808 0.71968277 0.92622905]
  [0.66754131 0.50834763 0.90794651]]

 [[0.75484945 0.98245849 0.42376296]
  [0.53439358 0.73643706 0.24717548]
  [0.89237703 0.64570156 0.19292652]]

 [[0.28377617 0.15317876 0.81381998]
  [0.88528162 0.99623782 0.01748771]
  [0.63129261 0.40070099 0.31783545]]]


array([[[0.73643706, 0.24717548],
        [0.64570156, 0.19292652]],

       [[0.99623782, 0.01748771],
        [0.40070099, 0.31783545]]])

In [ ]:
#update a sliced array
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

x[:,1:] = 1111
print(x)

[[   1 1111 1111]
 [   4 1111 1111]
 [   7 1111 1111]]


In [ ]:
#update a view
# its effect remains in the original variable
x = np.arange(1,10).reshape(3,3)

view = x[:, 1:]
view[:,:] = 0
print(x)


[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [ ]:
# to avoid updating orginal array
x = np.arange(1,10).reshape(3,3)
view = x[:,1:].copy()
x

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
x = np.array([1.2,4.1,1.5,4.5])
#x < 2.5

x2 = np.array([[1.2, 4.1], [1.5, 4.5]])
# this one returns the position with true and false
~((x2<1)|(x2>5))

# this one returns the values but eliminates the dimensions
x2[x2 > 1]


array([1.2, 4.1, 1.5, 4.5])

In [ ]:
# upadate a masked array
x2 = np.array([[1.2, 4.1], [1.5, 4.5]])
x2[x2 > 4] = 0
print(x2)

[[1.2 0. ]
 [1.5 0. ]]


In [ ]:
# mask does not create views, but copies
x2 = np.array([[1.2, 4.1], [1.5, 4.5]])
masked = x2[x2 > 4]
masked[:] = 0
print(x)

[1.2 4.1 1.5 4.5]


In [ ]:
# Fancy indexing
x = np.array([7.0, 9.0, 6.0, 5.0])
x[[1,2,3]]

array([9., 6., 5.])

In [ ]:
# just select rows form a 2D array
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], 
[6.0, 7.0, 8.0]])

x[[0,1,2]]

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], 
[6.0, 7.0, 8.0]])
print(x)
x[[1,2],[0,2]] # creates  [1,0],[2,2]
x[[1,2],[2,1]]

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([5., 7.])

In [ ]:
x = np.arange(1,28).reshape(3,3,3)
print(x)
x[[1,2],[1,2]] # creates  [1,1],[2,2] which is depth = 1 and height = 1 _depth = 2 and height = 2

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([[13, 14, 15],
       [25, 26, 27]])

In [ ]:
# fancy indexing provides copies like maksing only views damage orginal data

x = np.array([1.2, 4.1, 1.5, 4.5])
x[[1,3]] = 0
print(x)

x = np.array([1.2, 4.1, 1.5, 4.5])
sel = x[[1,3]]
sel[:] = 0
x

[1.2 0.  1.5 0. ]


array([1.2, 4.1, 1.5, 4.5])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])

np.concatenate((x,y), axis = 1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
np.concatenate((x,y), axis = 1)
np.hstack((x,y))
np.vstack((x,y))




array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [ ]:
x = np.array([1,2,3])
y = np.array([11,12,13])

# does not possible
#np.concatenate((x,y), axis = 1)
v = np.vstack((x,y))
v

array([[ 1,  2,  3],
       [11, 12, 13]])

In [ ]:
x = np.array([7, 7, 9, 9, 8, 8])
np.split(x,[2,4])
np.split(x,6)

[array([7]), array([7]), array([9]), array([9]), array([8]), array([8])]

In [ ]:
x = np.array([1,2,3])
x.reshape(-1,1)
x

array([1, 2, 3])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
res = arr[np.newaxis,:,:]
res

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#row vector to column vector
arr = np.array([[1,2,3],[4,5,6]])

res = arr[:, np.newaxis]
res

#or
#arr.reshape(-1,1)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

________________________________________________________________________________

*italicized text*# Numpy Examples

## 1) Computation with arrays

### a) Sigmoid activation function of a vector

In [ ]:
import numpy as np
x = np.array([4, -1, 7, 9, 3, -5])

**Apply the Sigmoid activation function: $y = sigmoid(x)$**
$$sigmoid(x_i) = \frac{1}{1+exp(-x_i)}$$
<img src='./sigmoid.png' width='40%'>

In [ ]:
def sigmoid (x):
  return 1/(1+np.exp(-x))
y = []
for x_i in x:
  y.append(sigmoid(x_i))
print(y)


[0.9820137900379085, 0.2689414213699951, 0.9990889488055994, 0.9998766054240137, 0.9525741268224334, 0.0066928509242848554]


In [ ]:
def sigmoid (x):
  return 1/(1+np.exp(-x))
print(sigmoid(x))

[0.98201379 0.26894142 0.99908895 0.99987661 0.95257413 0.00669285]


### b) Softmax activation function

Activation function that normalizes the input vector (z) to a discrete probability distribution (values of the result add to 1).

$$y_i = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [ ]:
yi = np.exp(x)/np.sum(np.exp(x))
print(yi)

# This is how to access a single entry
#print(np.exp(x[0])/(np.sum(np.exp(x))))

# it adds up to one
yi.sum()

[5.88673555e-03 3.96645122e-05 1.18238244e-01 8.73669020e-01
 2.16560899e-03 7.26480881e-07]


1.0000000000000002

In [ ]:
y = []
d = 0
for x_i in x:
  d += np.exp(x_i)
for x_i in x:
  y.append(np.exp(x_i)/d)

print(y)

[0.005886735552643246, 3.966451215134229e-05, 0.11823824429965747, 0.8736690201692363, 0.002165608985430459, 7.264808812617942e-07]


In [ ]:
y = []
sum_values = sum([np.exp(x_i) for x_i in x])
for x_i in x:
  y.append(np.exp(x_i)/sum_values)
print(y)

[0.005886735552643246, 3.966451215134229e-05, 0.11823824429965747, 0.8736690201692363, 0.002165608985430459, 7.264808812617942e-07]


## 2) Broadcasting: dataset normalization

In [ ]:
# Input table
n_samples = 100
n_columns = 5
mean = 1
std = 3
X = np.random.normal(mean, std, (n_samples, n_columns))

** Apply z-score: normalize each column by subtracting its mean and dividing by its standard deviation **

In [ ]:


X_norm = (X-X.mean(axis = 0))/X.std(axis = 0)

X_norm.std(axis = 0)

array([1., 1., 1., 1., 1.])

In [ ]:
Y = np.arange(1,10).reshape(3,3)
print(Y)
print(Y.mean(axis = 0))
print(Y.std(axis = 0))
(Y-Y.mean(axis = 0))/Y.std(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

## 3) Accessing Numpy Arrays

In [ ]:
#Input data
import numpy as np

# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1.4, 0.2],
           [4.3, 3. , 1.1, 0.1],
           [5. , 3.4, 1.6, 0.4],
           [5.1, 3.4, 1.5, 0.2],
           [6.9, 3.1, 4.9, 1.5],
           [6.7, 3.1, 4.4, 1.4],
           [6. , 2.9, 4.5, 1.5],
           [6.1, 3. , 4.6, 1.4],
           [6.5, 3. , 5.8, 2.2],
           [7.7, 3.8, 6.7, 2.2],
           [7.4, 2.8, 6.1, 1.9],
           [6.8, 3.2, 5.9, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2])


array([[5.1, 3.5, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.4, 1.5, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [6.7, 3.1, 4.4, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 3. , 5.8, 2.2],
       [7.7, 3.8, 6.7, 2.2],
       [7.4, 2.8, 6.1, 1.9],
       [6.8, 3.2, 5.9, 2.3]])

In [ ]:
# Get column indices
height_i = columns.index('height')
intensity_i = columns.index('intensity')

height_i,intensity_i

(0, 2, 5)

**Compute the average height:**

In [ ]:
X[:,height_i].mean()


6.133333333333334

**Compute the average height of samples with intensity greater than 5:**

In [ ]:
# My Solution
inte = X[:,intensity_i] 
print(inte > 5) #returns the position
#inte [inte>5].mean()
X[inte>5,height_i].mean()

[False False False False False False False False  True  True  True  True]


7.1000000000000005

In [ ]:
X[X[:,intensity_i]>5,height_i].mean()

7.1000000000000005

**Compute the probability of class 2 if intensity>5**
$$p = \frac{\#(intensity>5 \land class2)}{\#(intensity>5)}$$

In [ ]:
#My solution
#X[X[:,intensity_i]>5,intensity_i].size

d = (X[:,intensity_i]>5).sum()
n = ((labels == 2)&(X[:,intensity_i]>5)).sum()
p = n/d
p
#np.array([5,1]) & np.array([0,0])
#X[labels == 2,]

0.75

**Print the height of the top 3 records with highest intensity:**

In [ ]:
X[[np.argsort(X,axis=0)[:,intensity_i][-3:]],height_i]

array([[6.9, 7.4, 7.7]])

In [ ]:
X[[np.argsort(X[:,intensity_i])[-3:]],height_i]

array([[6.9, 7.4, 7.7]])

In [ ]:
# argmax return the postion of sorted value
X = np.array([[1,2],[2,5],[15,7],[8,0],[7,-5],[4,5]])
print(X)
X[[np.argsort(X[:,1], axis = 0)[-3:]],0]

[[ 1  2]
 [ 2  5]
 [15  7]
 [ 8  0]
 [ 7 -5]
 [ 4  5]]


array([[ 2,  4, 15]])

In [ ]:
# how to search a list inside other list
#create empty numpy
# append in numpy